export type Mode='mini'|'big';
export type Task={kind:'count'|'plus'|'divide'|'times';a:number;b:number;answer:number};
export type Journey={tasks:Task[];step:number;round:number;fish:number};
const roll=(max:number)=>1+Math.floor(Math.random()*max);
const pick=<T,>(items:T[])=>items[Math.floor(Math.random()*items.length)];
const shuffled=<T,>(items:T[])=>{const result=[...items];for(let i=result.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[result[i],result[j]]=[result[j],result[i]]}return result};
function miniPlus():Task{const pairs:{a:number;b:number}[]=[];for(let a=3;a<=17;a++)for(let b=2;b<=17;b++)if(a+b>=11&&a+b<=20)pairs.push({a,b});const {a,b}=pick(pairs);return {kind:'plus',a,b,answer:a+b}}
function miniTimes(kind:'times'|'divide'):Task{const pairs:{a:number;b:number}[]=[];for(let a=2;a<=9;a++)for(let b=2;b<=9;b++)if(a*b<=20)pairs.push({a,b});const {a,b}=pick(pairs);return kind==='times'?{kind,a,b,answer:a*b}:{kind,a:a*b,b:a,answer:b}}
export function makeTasks(mode:Mode,round=0):Task[]{if(mode==='mini')return shuffled([miniPlus(),miniPlus(),miniTimes('times'),miniTimes('divide'),miniTimes('divide')]);return Array.from({length:5},(_,i)=>{const b=[2,5,2,3,5][i],answer=roll(round>1?6:4);return i===2?{kind:'times',a:b,b:answer,answer:b*answer}:{kind:'divide',a:b*answer,b,answer}})}
export function taskText(t:Task){return t.kind==='count'?'Wie viele Fische siehst du?':t.kind==='plus'?`${t.a} plus ${t.b}. Wie viel ist das zusammen?`:t.kind==='times'?`${t.a} mal ${t.b}. Wie viel ist das?`:`${t.a} Fische für ${t.b} Pinguine. Wie viele bekommt jeder?`}
export function parseNumber(text:string):number|null{const s=text.toLowerCase().trim().replace(/[.!?,]/g,'');if(/^\d{1,2}$/.test(s))return Number(s);const words=['null','eins','zwei','drei','vier','fünf','sechs','sieben','acht','neun','zehn','elf','zwölf','dreizehn','vierzehn','fünfzehn','sechzehn','siebzehn','achtzehn','neunzehn','zwanzig'];const n=words.indexOf(s.replace(/^(das ist|es sind|die antwort ist|ich sage) /,''));return n>=0?n:s==='ein'||s==='eine'?1:null}
export function restore(raw:string|null):Journey|null{try{const x=JSON.parse(raw||'null');if(!x||!Number.isInteger(x.step)||x.step<0||x.step>5||!Number.isInteger(x.round)||x.round<0||!Number.isInteger(x.fish)||x.fish<0||!Array.isArray(x.tasks)||x.tasks.length!==5)return null;for(const t of x.tasks){if(!t||!['count','plus','divide','times'].includes(t.kind)||![t.a,t.b,t.answer].every(Number.isInteger)||t.a<1||t.a>50||t.b<0||t.b>10||t.answer<1||t.answer>50)return null;const answer=t.kind==='count'?t.a:t.kind==='plus'?t.a+t.b:t.kind==='divide'?t.a/t.b:t.a*t.b;if(answer!==t.answer)return null}return x}catch{return null}}
